### ISSUE TITLE
请问/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_pytorch_model.bin 应该放到本地哪个目录下？

### ISSUE THREAD

**Issue by g711ab** [Doubiiu/DynamiCrafter#49]
我的主机不能访问huggingface，/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_pytorch_model.bin 这个文件已经下载到本地，请问应该放到哪个目录下，谢谢！

**Comment by Doubiiu** [comment]
I am not sure about that, which is related to your own configuration.
One possible solution is adding 
```version: "<path to this bin file in your computer>"```
 under the `params` of `cond_stage_config` and `img_cond_stage_config` in each config yaml:
```
    cond_stage_config:
      target: lvdm.modules.encoders.condition.FrozenOpenCLIPEmbedder
      params:
        version: "<path to this bin file in your computer>"
        freeze: true
        layer: "penultimate"

    img_cond_stage_config:
      target: lvdm.modules.encoders.condition.FrozenOpenCLIPImageEmbedderV2
      params:
        version: "<path to this bin file in your computer>"
        freeze: true
```
I am not sure if it works or not and you can have a try.

**Comment by hben35096** [comment]
> 我的主机不能访问huggingface，/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_pytorch_model.bin 这个文件已经下载到本地，请问应该放到哪个目录下，谢谢！


https://www.codewithgpu.com/m/dynamicrafter_mo

hub.zip
解压后放入
/root/.cache/huggingface

如果是Windows系统，估计在：
C:\Users\这里是你的用户名\.cache\huggingface

**Comment by g711ab** [comment]
> I am not sure about that, which is related to your own configuration. One possible solution is adding `version: "<path to this bin file in your computer>"` under the `params` of `cond_stage_config` and `img_cond_stage_config` in each config yaml:
> 
> ```
>     cond_stage_config:
>       target: lvdm.modules.encoders.condition.FrozenOpenCLIPEmbedder
>       params:
>         version: "<path to this bin file in your computer>"
>         freeze: true
>         layer: "penultimate"
> 
>     img_cond_stage_config:
>       target: lvdm.modules.encoders.condition.FrozenOpenCLIPImageEmbedderV2
>       params:
>         version: "<path to this bin file in your computer>"
>         freeze: true
> ```
> 
> I am not sure if it works or not and you can have a try.

thank you for reply, but it is not work for me

**Comment by g711ab** [comment]
> > 我的主机不能访问huggingface，/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_pytorch_model.bin 这个文件已经下载到本地，请问应该放到哪个目录下，谢谢！
> 
> https://www.codewithgpu.com/m/dynamicrafter_mo
> 
> hub.zip 解压后放入 /root/.cache/huggingface
> 
> 如果是Windows系统，估计在： C:\Users\这里是你的用户名.cache\huggingface

非常感谢，但这个下载站点不太稳定，唯一一次下载成功但zip包无法打开，md5值如下：
c2cf1c93532560da93cc74f977cc9291  hub.zip

可以告诉我，.cache目录下的路径吗

**Comment by Doubiiu** [comment]
> > > 我的主机不能访问huggingface，/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_pytorch_model.bin 这个文件已经下载到本地，请问应该放到哪个目录下，谢谢！
> > 
> > 
> > https://www.codewithgpu.com/m/dynamicrafter_mo
> > hub.zip 解压后放入 /root/.cache/huggingface
> > 如果是Windows系统，估计在： C:\Users\这里是你的用户名.cache\huggingface
> 
> 非常感谢，路径已找到 .cache/huggingface/hub/models--laion--CLIP-ViT-H-14-laion2B-s32B-b79K/snapshots/de081ac0a0ca8dc9d1533eed1ae884bb8ae1404b/ 但还是不行

Maybe you can try my above solution by changing `version` path as  `<your path>/models--laion--CLIP-ViT-H-14-laion2B-s32B-b79K/blobs/<the file with filesize of ~4GB>`

**Comment by g711ab** [comment]
> .cache/huggingface/hub/models--laion--CLIP-ViT-H-14-laion2B-s32B-b79K/

    cond_stage_config:
      version: "/home/testaa/.cache/huggingface/hub/models--laion--CLIP-ViT-H-14-laion2B-s32B-b79K/blobs/open_clip_pytorch_model.bin"
      target: lvdm.modules.encoders.condition.FrozenOpenCLIPEmbedder
      params:
        freeze: true
        layer: "penultimate"

    img_cond_stage_config:
      version: "/home/testaa/.cache/huggingface/hub/models--laion--CLIP-ViT-H-14-laion2B-s32B-b79K/blobs/open_clip_pytorch_model.bin"
      target: lvdm.modules.encoders.condition.FrozenOpenCLIPImageEmbedderV2
      params:
        freeze: true

thank you ,it's my config file,This issue has not been resolved.

**Comment by Doubiiu** [comment]
First the `version` should be put under `params` like what I have mentioned here:
```
    cond_stage_config:
      target: lvdm.modules.encoders.condition.FrozenOpenCLIPEmbedder
      params:
        version: "xxxxx"
        freeze: true
        layer: "penultimate"

    img_cond_stage_config:
      target: lvdm.modules.encoders.condition.FrozenOpenCLIPImageEmbedderV2
      params:
        version: "xxxx"
        freeze: true
```
Second, what files were originally in your folder of `blobs` (instead of .bin)?
